### ISSUE TITLE
[LinesCounter] Скорость

### ISSUE THREAD

**Issue by pavel-b-novikov** [fink-artem/nsudotnet#1]
С какой скоростью работает IndexOf? Сколько раз вы его вызываете в ходе чтения файлов? В общем сообщите мне оценку вида O(f) вашего решения?

И перепишите его так, чтобы оно было, все же, несколько быстрее. 

Да-да. Эта задача о том, что встроенные инструменты не всегда хороши.

P.S. Вы зря ввязались в обработку кавычек. Я оценил попытку, но не стоило.

**Comment by fink-artem** [comment]
Я переписал
Действительно indexOf часто вызывался и не всегда это было нужно

**Comment by pavel-b-novikov** [comment]
> if (line[i] == '*') { if (i < length - 1 && line[i + 1] == '/') {

Если юзер решит подсунуть вам невалидный C#-файл, начинающийся со звездочки, то этот код выдаст ошибку.

**Comment by fink-artem** [comment]
Протестировал тысячу раз и так не смог найти когда же он выдаст мне ошибку
Вообще то, что вы описали не возможно
ведь он дойдёт до этого if только если где-то до этого было `/*` следовательно он не может выдать ошибку на невалидный C#-файл, начинающийся со звездочки.
ведь если файл начался со звёздочки, то следовательно `/*` ещё не было и следовательно он не попадёт в этот if
`if (line[i] == '*') { if (i < length - 1 && line[i + 1] == '/') {`

**Comment by pavel-b-novikov** [comment]
Окей, принято
