### ISSUE TITLE
[NumberGuesser] Int32

### ISSUE THREAD

**Issue by pavel-b-novikov** [fink-artem/nsudotnet#2]
Задам вопрос, который очень популярен на собеседованиях (внезапно).

Чем отличается int от Int32?

**Comment by fink-artem** [comment]
Ничем
Я когда навожу мышку на int вижу : struct System.Int32
то же самое при наведении на Int32
int это просто алиас класса System.Int32

**Comment by pavel-b-novikov** [comment]
Да, именно так. Не пойму почему этот вопрос задают.
