### ISSUE TITLE
[NumberGuesser] Minute

### ISSUE THREAD

**Issue by pavel-b-novikov** [fink-artem/nsudotnet#3]
> DateTime.Now.Minute - date.Minute

А если я тупой и играл больше одной минуты? 
Переделайте, пожалуйста, по-человечески. Чтобы с часами, минутами, вот это все...

**Comment by fink-artem** [comment]
Сделал минуты и часы

**Comment by pavel-b-novikov** [comment]
А дни, месяцы, годы? Опять не то.

**Comment by fink-artem** [comment]
Вообще в задание конкретно сказано вывести
`Время в минутах, которое пользователь затратил на весь процесс`
и зачем нам дни, месяцы, года
Тем более мы знаем что при отнимание DateTime - DateTime получается класс TimeSpan 
и из этого класса нельзя получить месяцы года.

**Comment by pavel-b-novikov** [comment]
Окей, это и требовалось
